### ISSUE TITLE
How to Add Template

### ISSUE THREAD

**Issue by charleswg** [neurolabusc/MRIcron#10]
Hi I'm trying to add Talairach template into the folder structure. I've generated the text label file.

However, it's not showing the text label nor using the LUT.

Is there some tricks to make it work?

Thanks.

Kelvin

**Comment by neurolabusc** [comment]
For MRIcron templates, open the image up with MRIcron and Window/Information

- In the `Dimensions` tab make sure the Data pulldown menu is `8-bit int U*` - uint8's are the only format allowed for templates. 
- In the `Statistics` tab set the `Intention` pull-down to `Labels`
- In the `Statistics` tab set the `Intention` pull-down to `Labels`
- In the `Optional` tab set the `Regular [114]` pull-down to `98`
Save you modified header (File/SaveHeader).

**Comment by charleswg** [comment]
Chris,

Thanks for the quick response. Does it mean it cannot be done for Talairach atlas? It has more than 255 labels. 

Best,
Kelvin

**Comment by neurolabusc** [comment]
Yes, with MRIcron a template can have at most 255 labels. If you have a template with more than 255 labels, I suggest you use [MRIcroGL](https://github.com/neurolabusc/MRIcroGL/releases). The inia19-NeuroMaps template included with the binary releases shows a template with 16-bit datatype. The other change with MRIcroGL is that you have the option to include the text label with embedded in the NIfTI header. From the users point of view this is convenient as one does not always make sure that both the NIfTI and text labels are in the same folder with the same name. It is also compatible with the MacOS sandboxing requirements. To embed the text file you would use a hex editor to insert the text file at byte 352 of the uncompressed (.nii, not .nii.gz) template. You then need to adjust the vox_offset (typically 352) to be 352+N where N is the number of bytes you inserted.

Also you may want to be mindful of the color coding used for your image, e.g. if you want symmetrical colors for the left and right hemisphere. The ImageJ LUT color table only allows 256 colors. Again, the inia19 image is a good guide.

**Comment by charleswg** [comment]
Thank you Chris for the detailed instructions.
