### ISSUE TITLE
Flip LR shows incorrect voxel values

### ISSUE THREAD

**Issue by EmilieMcKinnon** [neurolabusc/MRIcron#11]
When the flip LR option is checked the voxel values that are displayed at the top of the image are from the image before the image was flipped. Here is an example: 
<img width="1301" alt="screen shot 2018-12-04 at 7 59 02 am" src="https://user-images.githubusercontent.com/24574541/49444396-0aec8900-f79d-11e8-8875-f4c1b87252bc.png">

**Comment by neurolabusc** [comment]
The menu reports the last clicked location. Click a new location for an updated value.
