### ISSUE TITLE
Scripting for loading the first volume of a 4D image

### ISSUE THREAD

**Issue by chuanjigao** [neurolabusc/MRIcron#14]
Hi Chris,
I hope you are well. 
I'd like to use bash to load the first volumes of several 4-D images, but I'm not sure how to set this in code.
I know it will give me a prompt now to select which volume to show but I'd like to show it directly by setting this in the code:

#!/bin/sh
echo read subject $1
workdir="F:/KNOWLEDGE_DOING/dataScience_1_Toolbox/example_data/example_fmri_data_2"
echo working directory is: $workdir
start "F:/KNOWLEDGE_DOING/dataScience_1_Toolbox/ToolBox_Plot_MRI_mricron_201909/mricron.exe" $workdir/sub-$1/func/sub-$1_task-affect_bold.nii
start "F:/KNOWLEDGE_DOING/dataScience_1_Toolbox/ToolBox_Plot_MRI_mricron_201909/mricron.exe" $workdir/sub-$1/func/r_sub-$1_task-affect_bold.nii

I have looked up in the website but did not find how to set up loading only the first volume of the 4-d image:
https://people.cas.sc.edu/rorden/mricron/bat.html

Thanks in advance for any help!

**Comment by neurolabusc** [comment]
Chuanji,
 MRIcron's scripting abilities are very limited. I strongly suggest you use [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage#Scripting) which has a much more robust scripting language. With MRIcroGL, a script always initially loads the first volume of a 4D dataset, and you can select a specific volume within a 4D dataset by using the "volume" function. Be aware, that like Python, FSL and most. other programming languages (but not Matlab), the first item in an array is 0. Therefore, if you choose volume(0,2), you will be selecting the first layer (the background images) and the 3rd volume.

```
import gl
gl.resetdefaults()
gl.loadimage('~/fmri.nii')
gl.orthoviewmm(37,-14,47)
gl.volume(0,2)
```

**Comment by chuanjigao** [comment]
Thank you very much Chris! Very helpful!
