### ISSUE TITLE
MRIcron does not open the "*_desc-brain_mask.nii" files from fmriprep

### ISSUE THREAD

**Issue by lorisnaspi** [neurolabusc/MRIcron#17]
Hi MRIcron people,

I would like to just report an issue that I found within MRIcron. I finished the preprocessing using fmriprep and everything went OK. There were no errors to report. However, I realized that I was not able to open the newly created brain masks with MRIcron. Or better, the functional images were OK, but I just could not open the brain masks. You can find the whole thread linked here:

https://github.com/nipreps/fmriprep/issues/2507

When clicking on the mask MRIcron would throw an error: "Invalid floating point operation". However, I could open them with Nibabel thanks to Chris Markiewicz' s suggestion.

This means that this is a bug which is specifically related to MRIcron. I will attach here a couple of examples so that you can download and try yourself. Also, I cannot open them with MATLAB, which tells me that NaN values cannot be open.

Does any of have an idea of why this should be the case?

If there are any updates on this, or fixed bugs I am not aware, please tell me given that I d like to use MRIcron to quickly visualize them.

[sub-3000_ses-1_desc-brain_mask.nii.gz](https://github.com/neurolabusc/MRIcron/files/7016310/sub-3000_ses-1_desc-brain_mask.nii.gz)
[sub-3000_ses-1_dseg.nii.gz](https://github.com/neurolabusc/MRIcron/files/7016311/sub-3000_ses-1_dseg.nii.gz)
[sub-3000_ses-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz](https://github.com/neurolabusc/MRIcron/files/7016312/sub-3000_ses-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz)

best
Loris

**Comment by neurolabusc** [comment]
This is an issue with your images, not MRIcron. see my [comments](https://github.com/nipreps/fmriprep/issues/2507).

**Comment by effigies** [comment]
Thanks for taking a look, Chris. Apologies for the noise.
