### ISSUE TITLE
cannot select dicom files to convert to 4D nifti

### ISSUE THREAD

**Issue by nikinbaidar** [neurolabusc/MRIcron#22]
I'm trying to merge a bunch of fMRI .dcm slices to a 4D nifiti file but the dcm2niigui does not seem to let me select the files (I have read and write access to all the files and directories). I am running Arch Linux and this was working fine before a recent update. I've never had any trouble with this program until now. 
What command should i try to merge all the dicom slices into a 4D nifti file. I tried going through the help page but I got a bit lost. Thank you!

**Comment by neurolabusc** [comment]
I would strongly suggest using the latest version of [dcm2niix](https://github.com/rordenlab/dcm2niix) to convert DICOM files. If you want a graphical wrapper, use the `Import/ConvertDICOMtoNIfTI` menu item from [MRIcroGL](https://github.com/rordenlab/MRIcroGL/releases). Development switched from dcm2nii to dcm2niix in 2016, prior to the advent of manufacturers moving to enhanced DICOM. I am happy my older software remains popular, but I am unable to maintain those older tools. All the code is open source, so you can always extend my older tools if you wish.

**Comment by nikinbaidar** [comment]
> If you want a graphical wrapper, use the `Import/ConvertDICOMtoNIfTI` menu item from [MRIcroGL](https://github.com/rordenlab/MRIcroGL/releases).

**Comment by nikinbaidar** [comment]
> I would strongly suggest using the latest version of [dcm2niix](https://github.com/rordenlab/dcm2niix) to convert DICOM files. If you want a graphical wrapper, use the `Import/ConvertDICOMtoNIfTI` menu item from [MRIcroGL](https://github.com/rordenlab/MRIcroGL/releases). Development switched from dcm2nii to dcm2niix in 2016, prior to the advent of manufacturers moving to enhanced DICOM. I am happy my older software remains popular, but I am unable to maintain those older tools. All the code is open source, so you can always extend my older tools if you wish.

Thank you! I think I'll give that a shot.

**Comment by nikinbaidar** [comment]
Okay I tried using the ConvertDICOMtoNIfTI GUI but I cannot seem to drag and drop the folder that contains the dicom files. Also it does not seem there's an import option with that. Again, i tried using the dcm2nii from the interface 
`dcm2niix -m 1 -f %f_%p_%t_%s ./`
I want to create a single 4D NIfTI file with all the fMRI volumes, but a bunch a JSON files are being create along with multiple .nii files. Just a few months back I could do this with dcm2niigui with real ease.

**Comment by neurolabusc** [comment]
For Linux, you can try either the (deprecated) GTK2 version or the QT version. I am not familiar with Arch Linux, but perhaps one of these versions will support drag and drop support. You can also press the `Select Folder to Convert` button in the graphical interface to select the source. You can also use the graphical interface to generate your command line. For example if you do not want the BIDS sidecar you can set that to `none` in the drop down menu. This will invoke the `-b n` switch:

```
dcm2niix -b n  -m 1 -f %f_%p_%t_%s ./
```

![Screen Shot 2022-09-02 at 11 03 30 AM](https://user-images.githubusercontent.com/8930807/188178466-6f5744c9-5647-485f-adf9-6a4b0e045504.png)

**Comment by nikinbaidar** [comment]
>```
> dcm2niix -b n  -m 1 -f %f_%p_%t_%s ./
> ```
Thanks mate! this helped tons.
