### ISSUE TITLE
Lazarus build fails

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcron#3]
I am getting the following [build log](https://bpaste.net/show/e71a4eef45d1). Can you help me figure out what's wrong? What's the difference between trying to build the `.lpi` and `.lpr`?

E.g. for MRIcroGL I am building the former, but here the latter.

**Comment by neurolabusc** [comment]
Looks like you are compiling to the GTK2 widgetset. I would generally choose either GTK2 or QT for Linux, WinAPI for windows, and Carbon or Cocoa for OSX. The code below is how I build the software, note the "--ws=cocoa" or "--ws=carbon". Also, in the example below I create a 64-bit executable: Cocoa can be either 64 or 32 bit, Carbon must be 32-bit
   lazbuild -B dcm2nii.lpr --ws=cocoa --cpu=x86_64 --os=darwin --compiler=/usr/local/bin/ppcx64
for Carbon you would choose
  lazbuild -B mricron.lpr --ws=carbon

**Comment by TheChymera** [comment]
> Looks like you are compiling to the GTK2 widgetset. I would generally choose either GTK2 or QT for Linux

So then why would you say me compiling with GTK2 is a probable issue?

**Comment by neurolabusc** [comment]
Yes, I do not use your build system, but on your system that is causing these problems I would start with running the command line option
   lazbuild -B dcm2nii.lpr
and see if that generates the errors that mention GTK2. The compiler should choose the Carbon widgetset, but I wonder if your usage of a Linux-style build system has encouraged it to use GTK. If that does fail, see if you can get things to compile with the Carbon widgetset
  lazbuild -B mricron.lpr --ws=carbon
or the Cocoa widgetset
 lazbuild -B mricron.lpr --ws=cocoa
Both should work fine. The Lazarus Carbon interface is more mature. However, you need to use Cocoa if you want to compile to a 64-bit executable. In theory the 64-bit compile might be a bit faster (more registers) and could open larger images (>2Gb), but in practice I think there is little benefit for MRIcron. On the other hand, the OpenGL calls with MRIcroGL appear to benefit hugely from being built to Cocoa relative to Carbon. I am not sure why, but the Carbon wrapper adds a lot of overhead to OpenGL.

**Comment by TheChymera** [comment]
@neurolabusc 

It may be (in part ) due to my build system, as `lazbuild -B --lazarusdir="/usr/share/lazarus/" mricron.lpr` seems to work just fine if I run it directly in the cloned repo. However `lazbuild -B --lazarusdir="/usr/share/lazarus/" mricron.lpr --ws=carbon` (and cocoa, gtk2, or gtk3 for that matter) give me something similar to:

```
Hint: (lazarus) [RunTool] /usr/bin/fpc "-iWTOTP"
Hint: (lazarus) [RunTool] /usr/bin/fpc "-va" "compilertest.pas"
Hint: (lazarus) Missing state file of FCL 1.0.1: /usr/share/lazarus/packager/units/x86_64-linux/FCL.compiled
Hint: (lazarus) normal output directory of package FCL 1.0.1 is not writable: "/usr/share/lazarus/packager/units/x86_64-linux/"
TParsedCompilerOptions.SetOutputDirectoryOverride New=/home/chymera/.lazarus/lib/units/x86_64-linux
Hint: (lazarus) Missing state file of LazUtils 1.0: /usr/share/lazarus/components/lazutils/lib/x86_64-linux/LazUtils.compiled
Hint: (lazarus) normal output directory of package LazUtils 1.0 is not writable: "/usr/share/lazarus/components/lazutils/lib/x86_64-linux/"
TParsedCompilerOptions.SetOutputDirectoryOverride New=/home/chymera/.lazarus/lib/LazUtils/lib/x86_64-linux
Hint: (lazarus) Missing state file of LCLBase 1.6.0.4: /usr/share/lazarus/lcl/units/x86_64-linux/LCLBase.compiled
Hint: (lazarus) normal output directory of package LCLBase 1.6.0.4 is not writable: "/usr/share/lazarus/lcl/units/x86_64-linux/"
TParsedCompilerOptions.SetOutputDirectoryOverride New=/home/chymera/.lazarus/lib/LCLBase/units/x86_64-linux
Hint: (lazarus) Missing state file of LCL 1.6.0.4: /usr/share/lazarus/lcl/units/x86_64-linux/carbon/LCL.compiled
Error: (lazarus) unable to create package output directory "/usr/share/lazarus/lcl/units/x86_64-linux/carbon" of package "LCL 1.6.0.4"
Hint: (lazarus) normal output directory of package LCL 1.6.0.4 is not writable: "/usr/share/lazarus/lcl/units/x86_64-linux/carbon/"
TParsedCompilerOptions.SetOutputDirectoryOverride New=/home/chymera/.lazarus/lib/units/x86_64-linux/carbon
Hint: (lazarus) Last compile was incomplete for LCL 1.6.0.4
  State file="/home/chymera/.lazarus/lib/units/x86_64-linux/carbon/LCL.compiled"
Info: (lazarus) Execute Title="Compile package LCL 1.6.0.4"
Info: (lazarus) Working Directory="/usr/share/lazarus/lcl/interfaces/"
Info: (lazarus) Executable="/usr/bin/fpc"
Info: (lazarus) Param[0]="-MObjFPC"
Info: (lazarus) Param[1]="-Scghi"
Info: (lazarus) Param[2]="-Cg"
Info: (lazarus) Param[3]="-O1"
Info: (lazarus) Param[4]="-g"
Info: (lazarus) Param[5]="-gl"
Info: (lazarus) Param[6]="-l"
Info: (lazarus) Param[7]="-vewnhibq"
Info: (lazarus) Param[8]="-vm5044"
Info: (lazarus) Param[9]="-Fi/usr/share/lazarus/lcl/interfaces/carbon"
Info: (lazarus) Param[10]="-Fi/usr/share/lazarus/lcl/interfaces/carbon/objc"
Info: (lazarus) Param[11]="-Fi/usr/share/lazarus/lcl/interfaces/carbon/pascocoa/appkit"
Info: (lazarus) Param[12]="-Fi/usr/share/lazarus/lcl/interfaces/carbon/pascocoa/foundation"
Info: (lazarus) Param[13]="-Fu/usr/share/lazarus/lcl/interfaces/carbon"
Info: (lazarus) Param[14]="-Fu/usr/share/lazarus/lcl/interfaces/carbon/objc"
Info: (lazarus) Param[15]="-Fu/usr/share/lazarus/lcl/interfaces/carbon/pascocoa/appkit"
Info: (lazarus) Param[16]="-Fu/usr/share/lazarus/lcl/interfaces/carbon/pascocoa/foundation"
Info: (lazarus) Param[17]="-Fu/home/chymera/.lazarus/lib/units/x86_64-linux"
Info: (lazarus) Param[18]="-Fu/home/chymera/.lazarus/lib/LazUtils/lib/x86_64-linux"
Info: (lazarus) Param[19]="-Fu/home/chymera/.lazarus/lib/LCLBase/units/x86_64-linux"
Info: (lazarus) Param[20]="-Fu/usr/share/lazarus/lcl/interfaces/"
Info: (lazarus) Param[21]="-FU/home/chymera/.lazarus/lib/units/x86_64-linux/carbon"
Info: (lazarus) Param[22]="-dcarbon"
Info: (lazarus) Param[23]="lcl.pas"
Hint: (11030) Start of reading config file /etc/fpc.cfg
Hint: (11031) End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 3.0.0 [2016/05/06] for x86_64
Copyright (c) 1993-2015 by Florian Klaempfl and others
(1002) Target OS: Linux for x86-64
(3104) Compiling lcl.pas
(3104) Compiling ./carbon/alllclintfunits.pas
(3104) Compiling ./carbon/carbonprivate.pp
/usr/share/lazarus/lcl/interfaces/./carbon/carbonprivate.pp(28,3) Fatal: (10022) Can't find unit MacOSAll used by CarbonPrivate
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile package LCL 1.6.0.4: stopped with exit code 256
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 256"
ERROR: Project dependencies of /home/chymera/src/MRIcron/mricron.lpi
An unhandled exception occurred at $0000000000534713:
EAccessViolation: Access violation
  $0000000000534713
  $000000000056BE95
  $000000000056FE67
  $0000000000571071
```

**Comment by neurolabusc** [comment]
The log suggests you need write permissions to build the new widget sets. So set your permissions or perhaps use sudo

**Comment by TheChymera** [comment]
Since compiling from the cloned repo without specifying any `--ws` works, whereas doing it via the package manager does not, I'll be continuing this discussion [on the Portage side](https://github.com/gentoo-science/sci/issues/633). Still, it would be really helpful if you could chip in - none of us really knows a lot about lazarus.
