### ISSUE TITLE
Rendering lighting and overlay options are not saved

### ISSUE THREAD

**Issue by lrq3000** [neurolabusc/MRIcron#4]
When displaying the rendering window, there is a "Save settings" function in File. But the saved settings file doesn't store the two lighting sliders value (between the high-res button and the shading box), nor the "Overlay > Transparency on other overlays" option.

BTW it's a very great software, and it's perfect to overlap multiple overlays thank's to the color additive feature (actually it's surprisingly one of the only few able to do that, with MRIcroGL and Mango).

**Comment by neurolabusc** [comment]
OK, I have added the requested change to the source code. You may want to compile your own copy and test. While I feel this software is stable, mature and useful, it is not a tool I am actively developing. Most of my development efforts have shifted to MRIcroGL. For MRIcroGL the additive color feature is enabled with the menu item Overlays/TransparencyOnOtherOverlays/Additive.

**Comment by lrq3000** [comment]
Oh thank you very much, that was fast!

Yes I like MRIcroGL a lot, and I plan on making it my default visualization software, but there are some "issues" that are preventing me from using it. I will open issues when I'll have time. But the main one is that there's no on-gui option to set the camera at a specific common angle (left, right, behind, front, below, top) nor to save the current camera angle, so I can't easily generate a set of images with the same camera angles. I know there is the amazing scripting support that I can use to set specific angles, but it's not useable by non-developpers.

**Comment by neurolabusc** [comment]
You can make an enhancement request on the MRIcroGL github page. The following tiny MRIcroGL script is all you need to set the camera position. Just cut and paste in the Scripting window and then use the Scripting Forms' "Save as" option to make this a script you can run whenever you want. The first number is the Azimuth (0..360 degrees) and the second is the elevation (-90..90 degrees).

BEGIN
    AZIMUTHELEVATION(90, 25);
END.

**Comment by lrq3000** [comment]
Yes I will do in a few days, thank you!

2016-06-11 19:52 GMT+02:00 Chris Rorden notifications@github.com:

**Comment by lrq3000** [comment]
Just a quick update and a BIG THANK YOU for implementing the quick orientations shortcuts in MRIcroGL, I indeed forgot to open an issue to request that, but it's now implemented and it's perfect, I now use MRIcroGL all the time! :-D

**Comment by lrq3000** [comment]
(But I still use MRIcron for my day-to-day quick peak at nifti files, I think the interface is really perfect for that purpose, but MRIcroGL is great to have very nice visualizations for reports and publications, so I think both are complementary tools :-) Thank you very much for making them! I will consistently cite them in my articles :-) )
