### ISSUE TITLE
Compilation "stopped with exit code 256"

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcron#5]
With both the latest and the live version of MRIcron I get the following compilation failures:

* [=mricron-9999](http://bpaste.net/show/5069437666bd)
* [=mricron-1.0.20180404](http://bpaste.net/show/58632aa60fa2)

This is not mitigated either by explicitly selecting the `gtk2` widget set, or by trying to compile the `.lpr` file instead.

Any ideas how this could be fixed?

**Comment by neurolabusc** [comment]
The latest code uses the new high-resolution bitmaps, which will require the Lazarus 1.9 SVN to compile. I have uploaded a fairly recent compiled version as a pre-release
  https://github.com/neurolabusc/MRIcron/releases
that compiled version requires 24-bit color (it will fail on 16-bit color). 16-bit support will be restored in the upcoming release version. Please do test the pre-release and provide any comments. I hope to push out a stable release as soon as a new version of dcm2niix is released.

Unfortunately, the stable Lazarus 1.8.2 compiler does not support these features. The high-resolution bitmaps and a lot of MacOS changes have required a jump to the developmental 1.9 branch. The next major release of Lazarus is a quantum leap forward.
