### ISSUE TITLE
Cannot open large images

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcron#6]
Analogously to https://github.com/neurolabusc/MRIcroGL/issues/21, MRIcron is unable to load the largest image (it performs somewhat better than MRIcroGL, failing only at 0.016 instead of 0.017).

Additionally, there is a typo in the warning, it reads:

```Unable to load this image (to large or corrupt)``` (with a single o).

**Comment by neurolabusc** [comment]
Typo fixed - file size limited to 2Gb per volume when uncompressed.
